import type {
  CalendarAttendee,
  CalendarState,
  FunnelAnalytics,
} from "./domain";

const days = [1, 2, 3, 4, 5, 6, 0] as const;
const baseWindows = days.map(day => ({
  day,
  enabled: day >= 1 && day <= 5,
  start: "09:00",
  end: "17:00",
}));

const emptyAnalytics = (): FunnelAnalytics => ({
  views: 0,
  slotViews: 0,
  starts: 0,
  requests: 0,
  confirmed: 0,
});


/** @internal Deterministic fixture for domain tests. Runtime storage starts empty. */
export function createInitialCalendarState(): CalendarState {
  const self: CalendarAttendee = {
    id: "user-alex",
    name: "Alex Morgan",
    email: "alex@example.com",
    kind: "tap",
    required: true,
  };
  const maya: CalendarAttendee = {
    id: "user-maya",
    name: "Maya Chen",
    email: "maya@example.com",
    kind: "tap",
    required: true,
  };
  const theo: CalendarAttendee = {
    id: "user-theo",
    name: "Theo Martin",
    email: "theo@example.com",
    kind: "tap",
    required: true,
  };

  return {
    schemaVersion: 1,
    activeView: "work-week",
    accounts: [
      {
        id: "acct-icloud",
        provider: "icloud",
        label: "iCloud",
        status: "attention",
        calendars: [
          {
            id: "cal-home",
            accountId: "acct-icloud",
            name: "Home",
            color: "#5cc8f5",
            role: "owner",
            visible: true,
            conflicts: true,
            writable: true,
            destination: false,
            freshness: "delayed",
          },
          {
            id: "cal-family",
            accountId: "acct-icloud",
            name: "Family",
            color: "#a78bfa",
            role: "writer",
            visible: true,
            conflicts: true,
            writable: true,
            destination: false,
            freshness: "delayed",
          },
        ],
      },
      {
        id: "acct-google",
        provider: "google",
        label: "alex.personal@example.com",
        status: "connected",
        calendars: [
          {
            id: "cal-google-main",
            accountId: "acct-google",
            name: "alex.personal@example.com",
            color: "#93c5fd",
            role: "owner",
            visible: true,
            conflicts: true,
            writable: true,
            destination: false,
            freshness: "live",
          },
          {
            id: "cal-holidays",
            accountId: "acct-google",
            name: "Holidays in United States",
            color: "#34d399",
            role: "reader",
            visible: false,
            conflicts: false,
            writable: false,
            destination: false,
            freshness: "live",
          },
        ],
      },
      {
        id: "acct-microsoft",
        provider: "microsoft",
        label: "alex@example.com",
        status: "connected",
        calendars: [
          {
            id: "cal-work",
            accountId: "acct-microsoft",
            name: "Zephyr Cloud",
            color: "#22c55e",
            role: "owner",
            visible: true,
            conflicts: true,
            writable: true,
            destination: true,
            freshness: "live",
            unreadCount: 17,
          },
          {
            id: "cal-dmitry",
            accountId: "acct-microsoft",
            name: "shared.calendar@example.com",
            color: "#f97316",
            role: "free-busy",
            visible: true,
            conflicts: false,
            writable: false,
            destination: false,
            freshness: "live",
            unreadCount: 5,
          },
          {
            id: "cal-charlie",
            accountId: "acct-microsoft",
            name: "Transferred from archived.calendar@example.com",
            color: "#e879f9",
            role: "writer",
            visible: false,
            conflicts: false,
            writable: true,
            destination: false,
            freshness: "live",
          },
        ],
      },
      {
        id: "acct-exchange",
        provider: "exchange",
        label: "Contoso Exchange SE",
        status: "read-only",
        calendars: [
          {
            id: "cal-contoso",
            accountId: "acct-exchange",
            name: "Advisory board",
            color: "#facc15",
            role: "reader",
            visible: false,
            conflicts: false,
            writable: false,
            destination: false,
            freshness: "stale",
          },
        ],
      },
    ],
    events: [
      {
        id: "event-product",
        calendarId: "cal-work",
        title: "TAP product review",
        start: "2026-08-10T13:00:00-04:00",
        end: "2026-08-10T14:00:00-04:00",
        kind: "meeting",
        status: "confirmed",
        location: "tap-huddle",
        attendees: [self, maya, theo],
      },
      {
        id: "event-design",
        calendarId: "cal-work",
        title: "Calendar design critique",
        start: "2026-08-11T10:00:00-04:00",
        end: "2026-08-11T11:00:00-04:00",
        kind: "meeting",
        status: "confirmed",
        location: "google-meet",
        attendees: [self, maya],
      },
      {
        id: "event-focus",
        calendarId: "cal-google-main",
        title: "Focus: provider adapters",
        start: "2026-08-12T09:00:00-04:00",
        end: "2026-08-12T11:00:00-04:00",
        kind: "focus",
        status: "confirmed",
        location: null,
        attendees: [self],
      },
      {
        id: "event-school",
        calendarId: "cal-family",
        title: "School pickup",
        start: "2026-08-12T15:00:00-04:00",
        end: "2026-08-12T15:30:00-04:00",
        kind: "meeting",
        status: "confirmed",
        location: "physical",
        attendees: [self],
      },
      {
        id: "event-work-block",
        calendarId: "cal-work",
        title: "Prepare launch notes",
        start: "2026-08-13T11:00:00-04:00",
        end: "2026-08-13T12:30:00-04:00",
        kind: "work-block",
        status: "confirmed",
        location: null,
        attendees: [self],
        source: {
          kind: "task",
          id: "task-calendar-launch",
          label: "Task · Calendar launch checklist",
        },
      },
      {
        id: "event-customer",
        calendarId: "cal-work",
        title: "Customer architecture call",
        start: "2026-08-14T14:00:00-04:00",
        end: "2026-08-14T14:30:00-04:00",
        kind: "meeting",
        status: "confirmed",
        location: "zoom",
        attendees: [
          self,
          {
            id: "guest-jordan",
            name: "Jordan Lee",
            email: "jordan@example.com",
            kind: "external",
            required: true,
          },
        ],
      },
      {
        id: "event-dmitry",
        calendarId: "cal-dmitry",
        title: "Busy",
        start: "2026-08-14T10:00:00-04:00",
        end: "2026-08-14T12:00:00-04:00",
        kind: "meeting",
        status: "confirmed",
        location: null,
        attendees: [theo],
      },
    ],
    availability: [
      {
        id: "availability-standard",
        name: "Standard working hours",
        timezone: "America/New_York",
        preferredStart: "10:00",
        preferredEnd: "15:00",
        windows: baseWindows,
        bufferBeforeMinutes: 5,
        bufferAfterMinutes: 10,
        minimumNoticeMinutes: 120,
        bookingHorizonDays: 60,
        overrides: [
          {
            id: "override-summit-travel",
            date: "2026-08-17",
            label: "Customer summit travel",
            available: false,
          },
        ],
      },
      {
        id: "availability-customer",
        name: "Customer calls",
        timezone: "America/New_York",
        preferredStart: "11:00",
        preferredEnd: "16:00",
        windows: baseWindows.map(window => ({
          ...window,
          start: "10:00",
          end: "16:00",
        })),
        bufferBeforeMinutes: 10,
        bufferAfterMinutes: 15,
        minimumNoticeMinutes: 240,
        bookingHorizonDays: 30,
        overrides: [],
      },
    ],
    activeAvailabilityId: "availability-standard",
    bookingProfiles: [
      {
        id: "profile-alex",
        ownerType: "individual",
        slug: "alex-morgan",
        displayName: "Alex Morgan",
        timezone: "America/New_York",
        published: true,
        eventTypes: [
          {
            id: "event-type-30min",
            slug: "30min",
            title: "30 minute meeting",
            description: "A focused conversation with Alex.",
            durationMinutes: 30,
            approvalRequired: false,
            location: "google-meet",
            destinationCalendarId: "cal-work",
            availabilityScheduleId: "availability-standard",
            active: true,
            color: "#6d5dfc",
            analytics: {
              views: 842,
              slotViews: 516,
              starts: 244,
              requests: 197,
              confirmed: 184,
            },
          },
          {
            id: "event-type-advisory",
            slug: "architecture-advisory",
            title: "Architecture advisory",
            description: "A 60 minute architecture working session.",
            durationMinutes: 60,
            approvalRequired: true,
            location: "microsoft-teams",
            destinationCalendarId: "cal-work",
            availabilityScheduleId: "availability-customer",
            active: true,
            color: "#10b981",
            analytics: {
              views: 238,
              slotViews: 119,
              starts: 71,
              requests: 52,
              confirmed: 41,
            },
          },
        ],
      },
      {
        id: "profile-tap",
        ownerType: "team",
        slug: "tap-product",
        displayName: "TAP Product",
        timezone: "America/New_York",
        published: true,
        eventTypes: [
          {
            id: "event-type-team-demo",
            slug: "team-demo",
            title: "TAP team demo",
            description: "Meet whichever product specialist is available.",
            durationMinutes: 45,
            approvalRequired: false,
            location: "zoom",
            destinationCalendarId: "cal-work",
            availabilityScheduleId: "availability-customer",
            active: true,
            color: "#f97316",
            analytics: emptyAnalytics(),
          },
        ],
      },
    ],
    bookingRequests: [
      {
        id: "booking-pending-1",
        eventTypeId: "event-type-advisory",
        eventId: "event-hold-1",
        guestName: "Avery Brooks",
        guestEmail: "avery@example.com",
        status: "pending",
        requestedAt: "2026-08-14T09:14:00-04:00",
        expiresAt: "2026-08-15T09:14:00-04:00",
      },
    ],
    notificationPreferences: {
      reminderMinutes: [10],
      system: true,
      tap: true,
      email: true,
      sms: false,
      whatsapp: false,
      telegram: false,
      quietHoursStart: "22:00",
      quietHoursEnd: "07:00",
    },
    notificationChannels: [
      {
        id: "channel-personal",
        name: "TAP Calendar · Alex",
        scope: "private",
        enabled: true,
        entries: [
          {
            id: "channel-entry-approval",
            createdAt: "2026-08-14T09:14:00-04:00",
            kind: "approval",
            title: "Meeting approval requested",
            summary: "Avery Brooks requested Architecture advisory · Mon, Aug 17 at 2:00 PM",
            bookingRequestId: "booking-pending-1",
            redacted: false,
          },
          {
            id: "channel-entry-booked",
            createdAt: "2026-08-13T16:22:00-04:00",
            kind: "booking",
            title: "Meeting scheduled",
            summary: "Jordan Lee booked Customer architecture call · Fri at 2:00 PM",
            redacted: false,
          },
        ],
      },
      {
        id: "channel-team",
        name: "TAP Product · Scheduling",
        scope: "team",
        enabled: true,
        entries: [
          {
            id: "channel-entry-team",
            createdAt: "2026-08-13T12:12:00-04:00",
            kind: "booking",
            title: "Team demo scheduled",
            summary: "External guest booked Team demo · Tue at 11:00 AM",
            redacted: true,
          },
        ],
      },
    ],
    workflowNodes: [
      {
        id: "tap-calendar.normalize-booking-created",
        kind: "trigger",
        name: "Normalize Booking created",
        description: "Normalizes a Booking-created payload delivered by the Calendar gateway.",
      },
      {
        id: "tap-calendar.normalize-booking-cancelled",
        kind: "trigger",
        name: "Normalize Booking cancelled",
        description: "Normalizes a Booking-cancelled payload delivered by the Calendar gateway.",
      },
      {
        id: "tap-calendar.draft-work-block",
        kind: "action",
        name: "Draft Work Block",
        description: "Prepares a task, channel, or message-linked Work Block for review.",
      },
      {
        id: "tap-calendar.prepare-channel-summary",
        kind: "action",
        name: "Prepare channel summary",
        description: "Prepares a permission-aware Calendar Channel Summary for delivery.",
      },
    ],
  };
}
