import {
  CALENDAR_ACTIVITY_LIMIT, CALENDAR_ACTIVITY_RETENTION_MS, isActivityTimestamp,
  type CalendarActivityEntry, type CalendarActivityProjection,
} from "../../tap-calendar/src/activity-contract";
import { CalendarMcpError, type McpOwner } from "./calendar-mcp-store";

/** The only client-originated activity is an availability save, which lives in
 * TAP storage. All provider/publication activity is generated by D1 transitions. */
export async function syncAvailabilityActivity(database: D1Database, owner: McpOwner, input: unknown): Promise<void> {
  const now = Date.now();
  if (!input || typeof input !== "object" || Array.isArray(input) || Object.keys(input).join() !== "entries") {
    throw new CalendarMcpError(400, "invalid_activity", "Availability activity requires saved receipts.");
  }
  const entries = (input as { entries?: unknown }).entries;
  if (!Array.isArray(entries) || entries.length > 64 || !entries.every(entry => entry && typeof entry === "object"
    && Object.keys(entry).length === 2 && typeof entry.id === "string" && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/u.test(entry.id)
    && isActivityTimestamp(entry.occurredAt) && Date.parse(entry.occurredAt) <= now + 300_000)) {
    throw new CalendarMcpError(400, "invalid_activity", "Availability activity receipts are invalid.");
  }
  const retained = entries.filter(entry => Date.parse(entry.occurredAt) >= now - CALENDAR_ACTIVITY_RETENTION_MS);
  if (retained.length) await database.batch(retained.map(entry => database.prepare(
    `INSERT OR IGNORE INTO calendar_activity_events
      (workspace_id, principal_id, event_key, activity_id, status_id, occurred_at)
      VALUES (?, ?, ?, 'availability-updated', 'saved', ?)`,
  ).bind(owner.workspace, owner.principal, `availability:${entry.id}`, entry.occurredAt)));
}

export async function readCalendarActivity(database: D1Database, owner: McpOwner): Promise<CalendarActivityProjection> {
  const through = new Date().toISOString();
  const retainedFrom = new Date(Date.parse(through) - CALENDAR_ACTIVITY_RETENTION_MS).toISOString();
  const session = database.withSession("first-primary");
  const results = await session.batch<Record<string, unknown>>([
    session.prepare("SELECT started_at FROM calendar_activity_coverage WHERE id = 1"),
    session.prepare(`SELECT activity_id AS activityId, status_id AS statusId, occurred_at AS occurredAt
      FROM calendar_activity_events WHERE workspace_id = ? AND principal_id = ? AND occurred_at >= ? AND occurred_at <= ?
      ORDER BY occurred_at DESC, event_key DESC LIMIT ?`)
      .bind(owner.workspace, owner.principal, retainedFrom, through, CALENDAR_ACTIVITY_LIMIT + 1),
  ]);
  const start = results[0]?.results[0]?.started_at;
  if (!isActivityTimestamp(start)) throw new CalendarMcpError(503, "activity_unavailable", "Calendar activity tracking is unavailable.");
  const entries = results[1]!.results as unknown as CalendarActivityEntry[];
  let availableFrom = start > retainedFrom ? start : retainedFrom;
  if (entries.length > CALENDAR_ACTIVITY_LIMIT) {
    // Exclude the entire boundary millisecond, including ties omitted by LIMIT.
    const boundary = new Date(Date.parse(entries[CALENDAR_ACTIVITY_LIMIT - 1]!.occurredAt) + 1).toISOString();
    if (boundary > availableFrom) availableFrom = boundary;
  }
  return { schemaVersion: 1, workspaceId: owner.workspace, userId: owner.principal,
    availableFrom: availableFrom > through ? through : availableFrom, availableThrough: through,
    entries: entries.slice(0, CALENDAR_ACTIVITY_LIMIT) };
}
