// @generated by protoc-gen-tap-zod. DO NOT EDIT.

export type JsonValue =
  | null
  | boolean
  | number
  | string
  | JsonValue[]
  | { [key: string]: JsonValue };

export type CreateTripRequest = {
  workspaceId: string;
  requestId: string;
  title: string;
  purpose:
    | "ROADIE_TRIP_PURPOSE_CONFERENCE"
    | "ROADIE_TRIP_PURPOSE_MEETUP"
    | "ROADIE_TRIP_PURPOSE_PODCAST"
    | "ROADIE_TRIP_PURPOSE_WORK"
    | "ROADIE_TRIP_PURPOSE_OTHER";
  location?: string | undefined;
};

export type CreateTripResponse = {
  trip?: RoadieTrip | undefined;
};

export type GetWorkspaceContextRequest = {
  workspaceId: string;
};

export type GetWorkspaceContextResponse = {
  workspaceId: string;
  currentMember?: RoadieMember | undefined;
  members: RoadieMember[];
};

export type ListTripsRequest = {
  workspaceId: string;
  ownerUserId?: string | undefined;
};

export type ListTripsResponse = {
  trips: RoadieTrip[];
};

export type RoadieMember = {
  userId: string;
  displayName: string;
  avatarUrl?: string | undefined;
  role:
    | "ROADIE_WORKSPACE_ROLE_OWNER"
    | "ROADIE_WORKSPACE_ROLE_ADMIN"
    | "ROADIE_WORKSPACE_ROLE_MEMBER"
    | "ROADIE_WORKSPACE_ROLE_VIEW_ONLY";
};

export type RoadieTrip = {
  tripId: string;
  workspaceId: string;
  ownerUserId: string;
  title: string;
  purpose:
    | "ROADIE_TRIP_PURPOSE_CONFERENCE"
    | "ROADIE_TRIP_PURPOSE_MEETUP"
    | "ROADIE_TRIP_PURPOSE_PODCAST"
    | "ROADIE_TRIP_PURPOSE_WORK"
    | "ROADIE_TRIP_PURPOSE_OTHER";
  location?: string | undefined;
  createdAtMs: number;
  updatedAtMs: number;
};

export const roadieService = {
  typeName: "tap.roadie.v1.RoadieService",
  pathPrefix: "/rpc/tap.roadie.v1.RoadieService/",
  routePath: "/rpc/:service/:rpcMethod",
  methods: {
    CreateTrip: {
      name: "CreateTrip",
      localName: "createTrip",
      path: "/rpc/tap.roadie.v1.RoadieService/CreateTrip",
      requestType: "tap.roadie.v1.CreateTripRequest",
      responseType: "tap.roadie.v1.CreateTripResponse",
      methodKind: "unary",
    },
    GetWorkspaceContext: {
      name: "GetWorkspaceContext",
      localName: "getWorkspaceContext",
      path: "/rpc/tap.roadie.v1.RoadieService/GetWorkspaceContext",
      requestType: "tap.roadie.v1.GetWorkspaceContextRequest",
      responseType: "tap.roadie.v1.GetWorkspaceContextResponse",
      methodKind: "unary",
    },
    ListTrips: {
      name: "ListTrips",
      localName: "listTrips",
      path: "/rpc/tap.roadie.v1.RoadieService/ListTrips",
      requestType: "tap.roadie.v1.ListTripsRequest",
      responseType: "tap.roadie.v1.ListTripsResponse",
      methodKind: "unary",
    },
  },
} as const;

export type RoadieServiceMethod = keyof typeof roadieService.methods;
