// @generated by protoc-gen-tap-zod. DO NOT EDIT.

import { z } from 'zod';
import type * as generated from './generated';

export const jsonValueSchema: z.ZodType<generated.JsonValue, generated.JsonValue> = /* @__PURE__ */ (() => z.lazy(() =>
  z.union([
    z.null(),
    z.boolean(),
    z.number(),
    z.string(),
    z.array(jsonValueSchema),
    z.record(z.string(), jsonValueSchema),
  ]),
))();

export const deleteTripRequestSchema: z.ZodType<generated.DeleteTripRequest> = /* @__PURE__ */ (() => z.object({
  workspaceId: z.string(),
  requestId: z.string(),
  tripId: z.string(),
})
)();

export type DeleteTripRequest = generated.DeleteTripRequest;

export const deleteTripResponseSchema: z.ZodType<generated.DeleteTripResponse> = /* @__PURE__ */ (() => z.object({
  tripId: z.string(),
})
)();

export type DeleteTripResponse = generated.DeleteTripResponse;

export const getWorkspaceContextRequestSchema: z.ZodType<generated.GetWorkspaceContextRequest> = /* @__PURE__ */ (() => z.object({
  workspaceId: z.string(),
})
)();

export type GetWorkspaceContextRequest = generated.GetWorkspaceContextRequest;

export const getWorkspaceContextResponseSchema: z.ZodType<generated.GetWorkspaceContextResponse> = /* @__PURE__ */ (() => z.object({
  workspaceId: z.string(),
  currentMember: z.lazy(() => roadieMemberSchema).optional(),
  members: z.array(z.lazy(() => roadieMemberSchema)).default([]),
})
)();

export type GetWorkspaceContextResponse = generated.GetWorkspaceContextResponse;

export const listTripsRequestSchema: z.ZodType<generated.ListTripsRequest> = /* @__PURE__ */ (() => z.object({
  workspaceId: z.string(),
  ownerUserId: z.string().optional(),
})
)();

export type ListTripsRequest = generated.ListTripsRequest;

export const listTripsResponseSchema: z.ZodType<generated.ListTripsResponse> = /* @__PURE__ */ (() => z.object({
  trips: z.array(z.lazy(() => roadieTripSchema)).default([]),
})
)();

export type ListTripsResponse = generated.ListTripsResponse;

export const putTripRequestSchema: z.ZodType<generated.PutTripRequest> = /* @__PURE__ */ (() => z.object({
  workspaceId: z.string(),
  requestId: z.string(),
  trip: z.lazy(() => roadieTripSchema).optional(),
})
)();

export type PutTripRequest = generated.PutTripRequest;

export const putTripResponseSchema: z.ZodType<generated.PutTripResponse> = /* @__PURE__ */ (() => z.object({
  trip: z.lazy(() => roadieTripSchema).optional(),
})
)();

export type PutTripResponse = generated.PutTripResponse;

export const roadieEngagementOutcomeSchema: z.ZodType<generated.RoadieEngagementOutcome> = /* @__PURE__ */ (() => z.object({
  audienceCount: z.number().optional(),
  audienceConfidence: z.enum(["ROADIE_METRIC_CONFIDENCE_CONFIRMED", "ROADIE_METRIC_CONFIDENCE_ESTIMATED", "ROADIE_METRIC_CONFIDENCE_DERIVED"]).optional(),
  highlight: z.string().optional(),
  outcome: z.string().optional(),
  followUpCount: z.number().optional(),
  links: z.array(z.lazy(() => roadieImpactLinkSchema)).default([]),
  updatedAtMs: z.number(),
})
)();

export type RoadieEngagementOutcome = generated.RoadieEngagementOutcome;

export const roadieEvidenceSchema: z.ZodType<generated.RoadieEvidence> = /* @__PURE__ */ (() => z.object({
  sourceKind: z.enum(["ROADIE_EVIDENCE_SOURCE_KIND_PASTED_TEXT", "ROADIE_EVIDENCE_SOURCE_KIND_OFFICIAL_SITE", "ROADIE_EVIDENCE_SOURCE_KIND_USER", "ROADIE_EVIDENCE_SOURCE_KIND_DEMO_FIXTURE"]),
  sourceLabel: z.string(),
  excerpt: z.string().optional(),
  capturedAtMs: z.number(),
  confidence: z.enum(["ROADIE_EVIDENCE_CONFIDENCE_HIGH", "ROADIE_EVIDENCE_CONFIDENCE_MEDIUM", "ROADIE_EVIDENCE_CONFIDENCE_LOW"]).optional(),
})
)();

export type RoadieEvidence = generated.RoadieEvidence;

export const roadieImpactLinkSchema: z.ZodType<generated.RoadieImpactLink> = /* @__PURE__ */ (() => z.object({
  label: z.string(),
  url: z.string(),
})
)();

export type RoadieImpactLink = generated.RoadieImpactLink;

export const roadieMemberSchema: z.ZodType<generated.RoadieMember> = /* @__PURE__ */ (() => z.object({
  userId: z.string(),
  displayName: z.string(),
  avatarUrl: z.string().optional(),
  role: z.enum(["ROADIE_WORKSPACE_ROLE_OWNER", "ROADIE_WORKSPACE_ROLE_ADMIN", "ROADIE_WORKSPACE_ROLE_MEMBER", "ROADIE_WORKSPACE_ROLE_VIEW_ONLY"]),
})
)();

export type RoadieMember = generated.RoadieMember;

export const roadieTimelineItemSchema: z.ZodType<generated.RoadieTimelineItem> = /* @__PURE__ */ (() => z.object({
  itemId: z.string(),
  title: z.string(),
  startAtMs: z.number(),
  timeZone: z.string(),
  kind: z.enum(["ROADIE_ITINERARY_ITEM_KIND_TALK", "ROADIE_ITINERARY_ITEM_KIND_SOCIAL", "ROADIE_ITINERARY_ITEM_KIND_MEETING", "ROADIE_ITINERARY_ITEM_KIND_TRAVEL", "ROADIE_ITINERARY_ITEM_KIND_HOTEL", "ROADIE_ITINERARY_ITEM_KIND_PERSONAL", "ROADIE_ITINERARY_ITEM_KIND_OTHER"]),
  engagementType: z.enum(["ROADIE_ENGAGEMENT_TYPE_TALK", "ROADIE_ENGAGEMENT_TYPE_PANEL", "ROADIE_ENGAGEMENT_TYPE_WORKSHOP", "ROADIE_ENGAGEMENT_TYPE_PODCAST", "ROADIE_ENGAGEMENT_TYPE_INTERVIEW", "ROADIE_ENGAGEMENT_TYPE_KEYNOTE", "ROADIE_ENGAGEMENT_TYPE_LIVESTREAM"]).optional(),
  evidence: z.array(z.lazy(() => roadieEvidenceSchema)).default([]),
  outcome: z.lazy(() => roadieEngagementOutcomeSchema).optional(),
  createdAtMs: z.number(),
  updatedAtMs: z.number(),
})
)();

export type RoadieTimelineItem = generated.RoadieTimelineItem;

export const roadieTripSchema: z.ZodType<generated.RoadieTrip> = /* @__PURE__ */ (() => z.object({
  tripId: z.string(),
  workspaceId: z.string(),
  ownerUserId: z.string(),
  title: z.string(),
  purpose: z.enum(["ROADIE_TRIP_PURPOSE_CONFERENCE", "ROADIE_TRIP_PURPOSE_MEETUP", "ROADIE_TRIP_PURPOSE_PODCAST", "ROADIE_TRIP_PURPOSE_WORK", "ROADIE_TRIP_PURPOSE_PERSONAL", "ROADIE_TRIP_PURPOSE_OTHER"]),
  location: z.string().optional(),
  createdAtMs: z.number(),
  updatedAtMs: z.number(),
  timeline: z.array(z.lazy(() => roadieTimelineItemSchema)).default([]),
  impactReport: z.lazy(() => roadieTripImpactReportSchema).optional(),
})
)();

export type RoadieTrip = generated.RoadieTrip;

export const roadieTripImpactReportSchema: z.ZodType<generated.RoadieTripImpactReport> = /* @__PURE__ */ (() => z.object({
  sourceText: z.string(),
  eventAttendance: z.number().optional(),
  attendanceConfidence: z.enum(["ROADIE_METRIC_CONFIDENCE_CONFIRMED", "ROADIE_METRIC_CONFIDENCE_ESTIMATED", "ROADIE_METRIC_CONFIDENCE_DERIVED"]).optional(),
  summary: z.string(),
  highlights: z.string().optional(),
  outcomes: z.string().optional(),
  sponsorValue: z.string().optional(),
  privateReflection: z.string().optional(),
  followUpCount: z.number().optional(),
  links: z.array(z.lazy(() => roadieImpactLinkSchema)).default([]),
  createdAtMs: z.number(),
  updatedAtMs: z.number(),
})
)();

export type RoadieTripImpactReport = generated.RoadieTripImpactReport;
