// @generated by protoc-gen-tap-zod. DO NOT EDIT.

import { z } from "zod";
import type * as generated from "./generated";

export const jsonValueSchema: z.ZodType<generated.JsonValue, generated.JsonValue> =
  /* @__PURE__ */ (() =>
    z.lazy(() =>
      z.union([
        z.null(),
        z.boolean(),
        z.number(),
        z.string(),
        z.array(jsonValueSchema),
        z.record(z.string(), jsonValueSchema),
      ]),
    ))();

export const createTripRequestSchema: z.ZodType<generated.CreateTripRequest> =
  /* @__PURE__ */ (() =>
    z.object({
      workspaceId: z.string(),
      requestId: z.string(),
      title: z.string(),
      purpose: z.enum([
        "ROADIE_TRIP_PURPOSE_CONFERENCE",
        "ROADIE_TRIP_PURPOSE_MEETUP",
        "ROADIE_TRIP_PURPOSE_PODCAST",
        "ROADIE_TRIP_PURPOSE_WORK",
        "ROADIE_TRIP_PURPOSE_OTHER",
      ]),
      location: z.string().optional(),
    }))();

export type CreateTripRequest = generated.CreateTripRequest;

export const createTripResponseSchema: z.ZodType<generated.CreateTripResponse> =
  /* @__PURE__ */ (() =>
    z.object({
      trip: z.lazy(() => roadieTripSchema).optional(),
    }))();

export type CreateTripResponse = generated.CreateTripResponse;

export const getWorkspaceContextRequestSchema: z.ZodType<generated.GetWorkspaceContextRequest> =
  /* @__PURE__ */ (() =>
    z.object({
      workspaceId: z.string(),
    }))();

export type GetWorkspaceContextRequest = generated.GetWorkspaceContextRequest;

export const getWorkspaceContextResponseSchema: z.ZodType<generated.GetWorkspaceContextResponse> =
  /* @__PURE__ */ (() =>
    z.object({
      workspaceId: z.string(),
      currentMember: z.lazy(() => roadieMemberSchema).optional(),
      members: z.array(z.lazy(() => roadieMemberSchema)).default([]),
    }))();

export type GetWorkspaceContextResponse = generated.GetWorkspaceContextResponse;

export const listTripsRequestSchema: z.ZodType<generated.ListTripsRequest> = /* @__PURE__ */ (() =>
  z.object({
    workspaceId: z.string(),
    ownerUserId: z.string().optional(),
  }))();

export type ListTripsRequest = generated.ListTripsRequest;

export const listTripsResponseSchema: z.ZodType<generated.ListTripsResponse> =
  /* @__PURE__ */ (() =>
    z.object({
      trips: z.array(z.lazy(() => roadieTripSchema)).default([]),
    }))();

export type ListTripsResponse = generated.ListTripsResponse;

export const roadieMemberSchema: z.ZodType<generated.RoadieMember> = /* @__PURE__ */ (() =>
  z.object({
    userId: z.string(),
    displayName: z.string(),
    avatarUrl: z.string().optional(),
    role: z.enum([
      "ROADIE_WORKSPACE_ROLE_OWNER",
      "ROADIE_WORKSPACE_ROLE_ADMIN",
      "ROADIE_WORKSPACE_ROLE_MEMBER",
      "ROADIE_WORKSPACE_ROLE_VIEW_ONLY",
    ]),
  }))();

export type RoadieMember = generated.RoadieMember;

export const roadieTripSchema: z.ZodType<generated.RoadieTrip> = /* @__PURE__ */ (() =>
  z.object({
    tripId: z.string(),
    workspaceId: z.string(),
    ownerUserId: z.string(),
    title: z.string(),
    purpose: z.enum([
      "ROADIE_TRIP_PURPOSE_CONFERENCE",
      "ROADIE_TRIP_PURPOSE_MEETUP",
      "ROADIE_TRIP_PURPOSE_PODCAST",
      "ROADIE_TRIP_PURPOSE_WORK",
      "ROADIE_TRIP_PURPOSE_OTHER",
    ]),
    location: z.string().optional(),
    createdAtMs: z.number(),
    updatedAtMs: z.number(),
  }))();

export type RoadieTrip = generated.RoadieTrip;
